# Generated by Django 2.1.7 on 2019-04-09 06:46

from django.db import migrations, models

def add_default(apps, schema_editor):
    doc_model = apps.get_model("doc", "Doc")
    db_alias = schema_editor.connection.alias
    doc_model.objects.using(db_alias).create(
        id=1
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('doc_value', models.TextField(verbose_name='内容')),
            ],
        ),
        migrations.RunPython(add_default),
    ]
