# Generated by Django 2.1.7 on 2019-04-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='update_user',
            field=models.CharField(default=1, max_length=32, verbose_name='上次更新用户'),
            preserve_default=False,
        ),
    ]
