# Generated by Django 2.1.7 on 2019-03-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_auto_20190314_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkdevice',
            name='intranet_ip',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='vlan_ip',
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='ip1',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP1'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='ip2',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP2'),
        ),
    ]
