# Generated by Django 2.1.7 on 2019-03-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0030_auto_20190314_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
