# Generated by Django 2.1.7 on 2019-03-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0031_networkdevice_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevicenode',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
