# Generated by Django 2.1.7 on 2019-03-27 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0032_networkdevicenode_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='value',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.NetworkDeviceNode', verbose_name='Value'),
        ),
    ]
