# Generated by Django 2.1.7 on 2019-03-27 08:23

import assets.models.network
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0034_auto_20190327_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkdevice',
            name='node',
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='nodes',
            field=models.ManyToManyField(default=assets.models.network.default_node, to='assets.Node', verbose_name='Nodes'),
        ),
    ]
