# Generated by Django 2.1.7 on 2019-03-27 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0035_auto_20190327_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkdevice',
            old_name='nodes',
            new_name='node',
        ),
    ]
