# Generated by Django 2.1.7 on 2019-03-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0036_auto_20190327_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='addr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='node',
            name='tel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='联系人电话'),
        ),
        migrations.AddField(
            model_name='node',
            name='user',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='联系人'),
        ),
    ]
