# Generated by Django 2.1.7 on 2019-03-28 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0037_auto_20190327_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdcNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='改动日期')),
                ('addr', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('user', models.CharField(blank=True, max_length=30, null=True, verbose_name='联系人')),
                ('tel', models.CharField(blank=True, max_length=30, null=True, verbose_name='联系人电话')),
                ('message', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '网络设备节点',
                'verbose_name_plural': '网络设备节点',
            },
        ),
        migrations.DeleteModel(
            name='NetworkDeviceNode',
        ),
        migrations.RemoveField(
            model_name='node',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='node',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='node',
            name='user',
        ),
        migrations.AddField(
            model_name='idcnode',
            name='node_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.Node'),
        ),
    ]
