# Generated by Django 2.1.7 on 2019-03-28 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0038_auto_20190328_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.Node')),
            ],
            options={
                'verbose_name': '业务线',
                'verbose_name_plural': '业务线',
            },
        ),
    ]
