# Generated by Django 2.1.7 on 2019-04-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0039_businessnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_virtual',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='是否是虚拟机'),
        ),
        migrations.AddField(
            model_name='asset',
            name='physical_machine',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='宿主机ip'),
        ),
    ]
