# Generated by Django 2.1.7 on 2019-04-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0040_auto_20190408_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='physical_machine',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='宿主机标识'),
        ),
    ]
