# Generated by Django 2.1.7 on 2019-03-21 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0032_networkdevicenode_message'),
        ('ops', '0005_auto_20181219_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_file_path', models.CharField(max_length=255, verbose_name='本地文件路径')),
                ('remove_file_path', models.CharField(max_length=255, verbose_name='远程文件路径')),
                ('status', models.SmallIntegerField(max_length=5, verbose_name='执行状态')),
                ('hosts', models.ManyToManyField(to='assets.Asset', verbose_name='主机')),
                ('run_as', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.SystemUser', verbose_name='远程执行用户')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Playbook名字')),
                ('messag', models.TextField(verbose_name='备注')),
                ('connect_as', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.SystemUser', verbose_name='远程连接用户')),
                ('hosts', models.ManyToManyField(to='assets.Asset', verbose_name='主机')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('task_module', models.CharField(choices=[('shell', 'shell'), ('service', 'service'), ('copy', 'copy'), ('yum', 'yum'), ('template', 'template'), ('win_iis', 'win_iis'), ('win_copy', 'win_copy'), ('win_shell', 'win_shell'), ('win_feature', 'win_feature')], max_length=64, verbose_name='模块')),
                ('task_cmd', models.TextField(verbose_name='任务内容')),
                ('run_as', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.SystemUser', verbose_name='远程执行用户')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='task',
            field=models.ManyToManyField(to='ops.Tasks', verbose_name='任务'),
        ),
    ]
