# Generated by Django 2.1.7 on 2019-03-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0007_auto_20190321_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.IntegerField(verbose_name='执行状态'),
        ),
    ]
