# Generated by Django 2.1.7 on 2019-03-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0008_auto_20190321_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='message',
            field=models.CharField(default=1, max_length=255, verbose_name='返回信息'),
            preserve_default=False,
        ),
    ]
