# Generated by Django 2.1.7 on 2019-03-26 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0010_auto_20190325_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='run_as',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='task',
        ),
        migrations.AddField(
            model_name='playlist',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ops.Tasks', verbose_name='任务'),
            preserve_default=False,
        ),
    ]
