# Generated by Django 2.1.7 on 2019-03-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0011_auto_20190326_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'playbook', 'verbose_name_plural': 'playbook'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
    ]
