# Generated by Django 2.1.7 on 2019-03-29 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0039_businessnode'),
        ('ops', '0012_auto_20190327_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='IisRestart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255, verbose_name='任务')),
                ('status', models.IntegerField(verbose_name='执行状态')),
                ('messag', models.TextField(verbose_name='备注')),
                ('hosts', models.ManyToManyField(to='assets.Asset', verbose_name='主机')),
                ('run_as', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.SystemUser', verbose_name='远程连接用户')),
            ],
            options={
                'verbose_name': 'playbook',
                'verbose_name_plural': 'playbook',
            },
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='connect_as',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='hosts',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='task',
        ),
        migrations.DeleteModel(
            name='PlayList',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
