# Generated by Django 2.1.7 on 2019-03-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0013_auto_20190329_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iisrestart',
            name='messag',
        ),
    ]
