# Generated by Django 2.1.7 on 2019-03-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0015_iisrestart_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='message',
            field=models.TextField(verbose_name='返回信息'),
        ),
        migrations.AlterField(
            model_name='iisrestart',
            name='message',
            field=models.TextField(verbose_name='返回信息'),
        ),
    ]
