# Generated by Django 2.1.7 on 2019-04-04 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0039_businessnode'),
        ('ops', '0016_auto_20190330_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='IisCreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255, verbose_name='站点名')),
                ('dom', models.CharField(max_length=255, verbose_name='绑定域名')),
                ('pool', models.CharField(max_length=255, verbose_name='应用池')),
                ('pdir', models.CharField(max_length=255, verbose_name='物理路径')),
                ('port', models.CharField(max_length=255, verbose_name='监听端口')),
                ('ip', models.CharField(max_length=255, verbose_name='bindip')),
                ('status', models.IntegerField(verbose_name='执行状态')),
                ('message', models.TextField(verbose_name='返回信息')),
                ('hosts', models.ManyToManyField(to='assets.Asset', verbose_name='主机')),
                ('run_as', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.SystemUser', verbose_name='远程连接用户')),
            ],
        ),
    ]
