# Generated by Django 2.1.7 on 2019-04-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0017_iiscreate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iiscreate',
            name='message',
        ),
        migrations.AddField(
            model_name='iiscreate',
            name='pool_message',
            field=models.TextField(default=1, verbose_name='应用池返回信息'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iiscreate',
            name='site_message',
            field=models.TextField(default=1, verbose_name='站点返回信息'),
            preserve_default=False,
        ),
    ]
