# Generated by Django 2.1.7 on 2019-04-12 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0041_auto_20190409_1446'),
        ('ops', '0018_auto_20190405_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrontabTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='定时任务名称')),
                ('crontab', models.CharField(max_length=128, verbose_name='定时任务计划时间')),
                ('shell_cmd', models.TextField(verbose_name='定时任务执行脚本')),
                ('status', models.IntegerField(verbose_name='执行状态')),
                ('message', models.TextField(verbose_name='返回信息')),
                ('comment', models.TextField(verbose_name='备注信息')),
                ('hosts', models.ManyToManyField(to='assets.Asset', verbose_name='主机')),
                ('run_as', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.SystemUser', verbose_name='远程连接用户')),
            ],
        ),
    ]
