# Generated by Django 2.1.7 on 2019-04-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0019_crontabtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crontabtask',
            name='crontab',
        ),
        migrations.AddField(
            model_name='crontabtask',
            name='crontab_day',
            field=models.CharField(default=1, max_length=32, verbose_name='定时任务-天'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crontabtask',
            name='crontab_hour',
            field=models.CharField(default=1, max_length=32, verbose_name='定时任务-时'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crontabtask',
            name='crontab_minute',
            field=models.CharField(default=1, max_length=32, verbose_name='定时任务—分'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crontabtask',
            name='crontab_month',
            field=models.CharField(default=2, max_length=32, verbose_name='定时任务-月'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crontabtask',
            name='crontab_week',
            field=models.CharField(default=9, max_length=32, verbose_name='定时任务-周'),
            preserve_default=False,
        ),
    ]
