# Generated by Django 2.1.7 on 2019-04-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0020_auto_20190415_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontabtask',
            name='crontab_day',
            field=models.CharField(default='*', max_length=32, verbose_name='定时任务-天'),
        ),
        migrations.AlterField(
            model_name='crontabtask',
            name='crontab_hour',
            field=models.CharField(default='*', max_length=32, verbose_name='定时任务-时'),
        ),
        migrations.AlterField(
            model_name='crontabtask',
            name='crontab_minute',
            field=models.CharField(default='*', max_length=32, verbose_name='定时任务—分'),
        ),
        migrations.AlterField(
            model_name='crontabtask',
            name='crontab_month',
            field=models.CharField(default='*', max_length=32, verbose_name='定时任务-月'),
        ),
        migrations.AlterField(
            model_name='crontabtask',
            name='crontab_week',
            field=models.CharField(default='*', max_length=32, verbose_name='定时任务-周'),
        ),
    ]
