# Generated by Django 2.1.7 on 2019-04-15 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0021_auto_20190415_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrontabLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='执行结果')),
                ('ctime', models.TimeField(auto_now=True, verbose_name='执行时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='crontabtask',
            name='message',
        ),
        migrations.AddField(
            model_name='crontabtask',
            name='corntab_log',
            field=models.OneToOneField(default=8, on_delete=django.db.models.deletion.CASCADE, to='ops.CrontabLog', verbose_name='执行结果'),
            preserve_default=False,
        ),
    ]
