# Generated by Django 2.1.7 on 2019-04-15 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0022_auto_20190415_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crontabtask',
            name='corntab_log',
        ),
        migrations.AddField(
            model_name='crontablog',
            name='corntab_task',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ops.CrontabTask', verbose_name='crontab任务'),
            preserve_default=False,
        ),
    ]
