# Generated by Django 2.1.7 on 2019-04-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0027_auto_20190415_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontabtask',
            name='name',
            field=models.CharField(max_length=128, verbose_name='定时任务名称'),
        ),
    ]
