# Generated by Django 2.1.7 on 2019-04-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0028_auto_20190415_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crontabtask',
            name='shell_cmd',
        ),
        migrations.AddField(
            model_name='crontabtask',
            name='scripts_path',
            field=models.CharField(default=1, max_length=128, verbose_name='脚本路径'),
            preserve_default=False,
        ),
    ]
