# Generated by Django 2.1.7 on 2019-04-17 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0029_auto_20190416_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontablog',
            name='corntab_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.CrontabTask', verbose_name='crontab任务'),
        ),
    ]
