# Generated by Django 2.1.7 on 2019-04-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0032_auto_20190418_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crontablog',
            name='corntab_task_',
        ),
        migrations.DeleteModel(
            name='CrontabLog',
        ),
    ]
